# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
production:
  adapter: postgresql
  database: Robot-movement
  encoding: unicode
  pool: 5
  

development:
  adapter: postgresql
  encoding: unicode
  database: Robot-movement
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: Robot-movement
  pool: 5
